apiVersion: apps/v1
kind: Deployment
metadata:
  name: desafio3-backend
  labels:
    app: desafio3-backend
spec:
  selector:
    matchLabels: 
      app: desafio3-backend
  replicas: 1
  template:
    metadata:
      labels:
        app: desafio3-backend
    spec:
      containers:
        - name: backend
          image: "rafaelsbarbosa/imersao-fc-desafio-3-backend:latest"
          ports:
            - containerPort: 3000